version: "2"

volumes:
  db-data:
    external: false

services:
  db:
    image: postgres
    env_file: ../../.env.production
    volumes:
      - db-data:/var/lib/postgresql/db-data

  app:
    build:
      context: ../../
      dockerfile: docker/production/Dockerfile
    env_file: ../../.env.production
    volumes:
      - $PWD:/usr/src/app
    ports:
      - "3030:3030"
    depends_on:
      - db
